### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by jinyiyangsonos** [DreamerMind/nnef#1]
I was trying to installed the following packages during the installation of the `sve-library-am-kws-nnet`:
`nnef @ git+https://github.com/DreamerMind/nnef.git@main
    # via torch-to-nnef
nnef_tools @ git+https://github.com/KhronosGroup/NNEF-Tools.git@e6733b055cebd0f5a6ab60f883f6714763ce9ec1
    # via torch-to-nnef`
and I met this error:

 building '_nnef' extension
      creating build/temp.linux-x86_64-cpython-37
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../cpp/include -I/mnt/disks/data/venv/include/python3.7m -c nnef.cpp -o build/temp.linux-x86_64-cpython-37/nnef.o -std=c++11
      nnef.cpp:18:35: fatal error: nnef/flat/flat_parser.h: No such file or directory
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

Could you help me to fix it?

**Comment by JulienBalianSonos** [comment]
It should be fixed now sorry
